### ISSUE TITLE
this dataset breaks exemplar()

### ISSUE THREAD

**Issue by DataStrategist** [mdneuzerling/exemplar#3]
```
exemplar::exemplar(readr::read_csv("https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/1041147/legal-aid-statistics-main-data-jul-sep-2021.csv"))
```

If you only analyze the first few thousand rows it's fine... I'm almost thinking that it's a data size thing? Didn't investigate too deeply

**Comment by mdneuzerling** [comment]
The issue is with the `subcat_5` column, first appearing with element 68922: "ecf - \xa0Other (see notes)\xa0". That's a character encoding issue.

I'd rather not deal with character encoding issues in this package. Instead, I've implemented a change in 0d8e5f50ff21495b086c8df69a26dd1f1fb66969 that will produce the following exemplar for this column instead:

```r
"sub_cat5" %in% colnames(data)
is.character(data[["sub_cat5"]])
# This character vector is not valid UTF-8, so further assertions have been skipped
```
